### ISSUE TITLE
Implement Mounted() optimization using openat2(RESOLVE_NO_XDEV)

### ISSUE THREAD

**Issue by kolyshkin** [moby/sys#25]
Currently, `Mounted()` have to consult mountinfo to figure out if the argument is a mount point.

This mountinfo parsing can be avoided by doing two stat() calls and comparing `dev_t`. Unfortunately, it is not working for bind mounts.

Now, with `openat2(RESOLVE_NO_XDEV)`, we might be able to implement a trick to do a similar check for bind mounts, thus eliminating the need to parse mountinfo entirely.

**Comment by cyphar** [comment]
You can use `RESOLVE_NO_XDEV` for both bind-mounts and regular mountpoints -- `RESOLVE_NO_XDEV` disables any `vfsmount` jumps -- which is what you want to detect here. Plus it's only one syscall to check each mountpoint (though ideally you'd do the check by first opening the directory then doing `openat2(dirfd, "..", {.resolve = RESOLVE_NO_XDEV})` -- since if you used whole paths you'd get `-EXDEV` if *any* component is a mountpoint crossing)

**Comment by kolyshkin** [comment]
Ah, I totally forgot I tried adding openat2 support to x/sys/unix and it got reverted.

Trying one more time: https://go-review.googlesource.com/c/sys/+/253057

(surely I can just use `unix.Syscall()` directly and define a few constants, but I'd rather not)

**Comment by kolyshkin** [comment]
I guess we have to check first if `path` is a file or directory. For non-directories, we need to use file's directory as dirfd and the file itself as a file. For directories, it is as described above

**Comment by kolyshkin** [comment]
Funny, it requires 5 syscalls.

1. `lstat` to figure out whether it's a directory or not.
2. `open` to open a directory.
3. `openat2` -- the actual check.
4. close for dirfd obtained in 2.
5. close for fd obtained in 3.
